app:
  debug: true # DEFAULT: false | Do not set to true if you are not a developer
  silent_debug: true # DEFAULT: false | Do not set to true if you are a developer and you know what it dose

database:
  host: 127.0.0.1 # DEFAULT: 127.0.0.1 | MYSQL_IP
  port: 3306 # DEFAULT: 3306 | MYSQL_PORT
  username: MythicalSystems # DEFAULT: MythicalSystems | MYSQL_USERNAME
  password: '<password>' # DEFAULT: <password> | MYSQL_PASSWORD
  database: mythicalwebpanel # DEFAULT: mythicalwebpanel | MYSQL_DATABASE_NAME